openapi: 3.0.0
info:
  title: traing
  version: 1.0.0
servers:
  - url: http://localhost:8080
paths:
  /hello:
    get:
      tags:
        - default
      summary: get
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}